### ISSUE TITLE
detect when payload is missing BIOS

### ISSUE THREAD

**Issue by cgwalters** [coreos/bootupd#787]
Today if e.g. `grub2-pc-modules` is missing (i.e. grub BIOS support) we claim we we have support for BIOS but fail at install time. I am not totally sure of the best way to detect this, but checking for `/usr/lib/grub/i386-pc` may be simplest.

**Comment by HuijingHei** [comment]
Makes sense, check all files in `grub2-pc-modules` are installed under `/usr/lib/grub/i386-pc`.
```
$ rpm -ql grub2-pc-modules
/usr/lib/grub/i386-pc
/usr/lib/grub/i386-pc/acpi.mod
/usr/lib/grub/i386-pc/xxx
```
